[package]
name = "hloo"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["bit_permute", "bit_permute_macro"]

[dependencies]
bit_permute = { path = "bit_permute" }
bit_permute_macro = { path = "bit_permute_macro" }
thiserror = "1"
memmap2 = { version = "0.7", optional = true }
tempfile = { version = "3", optional = true }

[dev-dependencies]
rand = "0.8"

[dev-dependencies.criterion]
version = "0.5"
default-features = false
features = ["cargo_bench_support", "html_reports"]

[features]
default = ["memmap_index"]
memmap_index = ["dep:memmap2", "dep:tempfile"]

[[bench]]
name = "all"
harness = false

[[bench]]
name = "internal"
harness = false
