unstable_features = true
max_width = 120
overflow_delimited_exprs = true
reorder_impl_items = true
imports_granularity = "Crate"
group_imports = "StdExternalCrate"
combine_control_expr = false
condense_wildcard_suffixes = true
