name: Test

on:
  push:
    branches:
      - "main"

jobs:
  test:
    strategy:
      matrix:
        os:
          - ubuntu-24.04
          - windows-2025
        toolchain:
          - 1.90.0
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: install rust
        run: |
          rustup toolchain install ${{ matrix.toolchain }} --profile minimal --no-self-update
          rustup default ${{ matrix.toolchain }}
      - name: run tests
        run: cargo test --all
